language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

os:
- linux

env:
- ARCH=x86_64
- ARCH=i686

node_js:
- '12'
- '10'
- '8'

script:
- gulp test
- gulp browserify
- gulp lint

before_install:
- npm i -g yarn@1.9.4

install:
- yarn
